#!/bin/bash
#########################################################
#   Filename   : btrfsrotate                            #
#   Description: TODO                                   #
#########################################################

PROGNAME="$(basename $0)"
quiet=false

set -u
set -e

# Prints help message
function showhelp {
    cat >&2 <<- EOF 
Usage: $PROGNAME [OPTION] ...
Options:
    -b  btrfs directory to rotate
    -c  max rotations to keep
    -t  adds tag to snapshotname
    -h  prints this help message.

Example:
    $PROGNAME -b /data -c 12 -t monthly 
    $PROGNAME -b /data -c 7 -t daily
EOF
}

# Prints log message to default output
function log {
    local level="$1"
    local message="$2"

    $quiet || echo "$(date +"%F %T" ) $PROGNAME: $message" 
}

while getopts "b:c:t:qh" opt
do
    case $opt in
        b)  directory=$OPTARG
            ;;
        c)  count=$OPTARG
            ;;
        t)  tag=$OPTARG
            ;;
        q)  quiet=true
            ;;
        h)  showhelp
            exit 1
            ;;
        *)  showhelp
            exit 1
            ;;
    esac
done  

echo $option


