#!/bin/bash
#########################################################
#	Name: 	updatetxt2blog 				#
#	Description: Mise a jour du blog 		#
#########################################################

executable="/home/remi/bin/txt2blog"
domain="priv.r-2b.net"
src="/home/remi/Developpements/private-source/$domain"
dst="/var/www/$domain"

test -x $executable && $executable $src $dst
